.\" Manpage for SetsCalc.
.\" Contact anton2920@gmail.com for comments or help.
.TH man 1 "09 Jul 2019" "1.0" "SetsCalc man page"
.SH NAME
SetsCalc
.SH SYNOPSIS
SetsCalc
.SH DESCRIPTION
SetsCalc is a free powerful sets calculator.
.SH OPTIONS
SetsCalc takes no arguments.
.SH BUGS
No known bugs.
.SH AUTHOR
anton2920 (anton2920@gmail.com)
